# Generated by Django 4.0.6 on 2022-12-05 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_consult_event_posttype_section_trud_tvor_volant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mesta_now',
            field=models.IntegerField(default=2, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Количество мест сейчас'),
        ),
    ]
