# Generated by Django 4.0.6 on 2022-12-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_mesta_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttype',
            old_name='group',
            new_name='zap_type',
        ),
    ]
