# Generated by Django 4.0.6 on 2022-12-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_posttype_options_post_mest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='colvo',
            field=models.IntegerField(null=True, verbose_name='Количество занятых мест'),
        ),
    ]
