# Generated by Django 4.0.6 on 2022-12-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_posttype_colvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vist',
            name='final_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Крайняя дата'),
        ),
    ]
